fix: support allow-unauthorized in aem up
adobe/helix-cli pull request #2352
Opened 2024-05-02 08:02 UTC by dominique-pfister

fix #2351

2024-05-02 08:08 UTC, dominique-pfister commented
There are more invocations of `getFetch()` in the code, hope this is the only one to fix for this issue.

2024-05-02 08:40 UTC, tripodsan requested changes
that's not enough.... search for all `getFetch()` calls :-)

2024-05-02 11:36 UTC, tripodsan commented on src/up.js
> +          describe: 'Whether to allow unauthorized access to server',
maybe this is not a very good description... I think `allowInsecure` would be better

2024-05-02 12:02 UTC, tripodsan commented on src/server/BaseServer.js
> +          const res = await getFetch(this._project.allowInsecure)(`${this._scheme}://${this._addr}:${this._port}/.kill`);
this is a request back to localhost, so if https, it most probably is a self-signed, to I would use `true` by default

2024-05-02 12:05 UTC, tripodsan requested changes
we should probably also add it here:
https://github.com/adobe/helix-cli/blob/ef79a85031259d242919baafd16b28a19a06aa46/src/server/HelixImportServer.js#L104C23-L104C29

IIRC, this was added because some imported sites had invalid certs, but I don't think this should be the default.

@kptdobe WDYT?

2024-05-02 12:30 UTC, kptdobe commented
`rejectUnauthorized: false` was introduced by https://github.com/adobe/helix-cli/pull/2040 in the importer server. 
To use the same logic than for `aem up`, `true` can be the default and the option would allow to disable it.

2024-05-02 12:34 UTC, tripodsan commented on src/up.js
> +        })
maybe also add this to `import.js` ?

2024-05-03 08:20 UTC, tripodsan approved these changes

2024-05-03 08:23 UTC, merged