fix #2354: Resources that redirect to protocol-relative URIs are not handled correctly
adobe/helix-cli pull request #2355
Opened 2024-05-03 18:48 UTC by blefebvre

## Related Issues

#2354

Please ensure your pull request adheres to the following guidelines:
- [x] make sure to link the related issues in this description
- [x] when merging / squashing, make sure the fixed issue references are visible in the commits, for easy compilation of release notes

2024-05-05 09:21 UTC, tripodsan requested changes
- simplify
- add test

2024-05-05 09:21 UTC, tripodsan commented on src/server/HelixImportServer.js
> +      }
I think this can be simplified, with:
```
const location = new URL(respHeaders.location, url);
```

2024-05-08 20:31 UTC, blefebvre commented
Thanks @tripodsan for the feedback.

2024-05-09 11:05 UTC, tripodsan approved these changes

2024-05-09 11:06 UTC, merged