WIP: feat: Allow AEM CLI to obtain site token
adobe/helix-cli pull request #2471
Opened 2024-12-30 17:26 UTC by andreituicu

2025-01-06 08:40 UTC, andreituicu commented on src/up.cmd.js
> +          `https://admin-ci.hlx.page/login/${org}/${site}/main?client_id=aem-cli&redirect_uri=${encodeURIComponent(`http://localhost:${this._httpPort}/.aem/cli/login/ack`)}`,
Reminder to switch to the production admin url, before merging.

2025-01-06 11:57 UTC, andreituicu commented on src/config/config-utils.js
> +    fs.writeFileSync(envFile, env, 'utf8');
Dismissing the alert as in [ec3d967](https://github.com/adobe/helix-cli/pull/2471/commits/ec3d967a80483439b30e4ac0c96584983f298b8a) I added validation that we are only writing into the file if there is a valid JWT, not arbitrary untrusted data.

2025-01-06 16:39 UTC, tripodsan commented
> Question: Ideally, `.env` would've been already present in `.gitignore` from the boilerplate. Created [adobe/aem-boilerplate#441](https://github.com/adobe/aem-boilerplate/pull/441), but this will unfortunately not add it to .gitignore retroactively for projects that already copied the boilerplate. Maybe another file under `.hlx/` would be more appropriate to store and read the token from?

on the one hand, I think updating gitignore as mentioned in step 7 is enough....
but, otoh, I don't like too much, that .env is modified, as this "belongs" to the user. maybe having a single `.hlx-auth-token` file be more transparent and less intrusive.

2025-01-07 10:16 UTC, andreituicu commented
> but, otoh, I don't like too much, that .env is modified, as this "belongs" to the user. maybe having a single .hlx-auth-token file be more transparent and less intrusive.

Sounds good to me, we can put it `.hlx`, because it's been in `.gitignore` since the beginning of the boilerplate ( https://github.com/adobe/aem-boilerplate/blame/main/.gitignore#L1C5-L1C5 ) and have `.hlx/.hlx-auth-token`. Let me give that a try.

The only small concern I have is that `.hlx` isn't removed from the boilerplate `.gitignore`, because of the old branding. 🙂

2025-01-08 11:32 UTC, tripodsan commented on src/config/config-utils.js
> +const tokenFilePath = path.join(hlxFolder, tokenFileName);
```suggestion
const tokenFilePath = path.resolve(hlxFolder, tokenFileName);
```

2025-01-08 11:33 UTC, tripodsan commented on src/config/config-utils.js
> +  if (!fs.existsSync(hlxFolder)) {
why sync ?

2025-01-08 11:35 UTC, tripodsan requested changes
questions around file I/O

2025-01-08 17:04 UTC, andreituicu commented on src/config/config-utils.js
> +  const tokenFile = fs.openSync(tokenFilePath, 'w+');
initially because of the github security bot recommendations:
* https://github.com/adobe/helix-cli/security/code-scanning/9
* https://github.com/adobe/helix-cli/security/code-scanning/19

but I found now simpler way to not having to do it.
should be fixed in [2cfde06](https://github.com/adobe/helix-cli/pull/2471/commits/2cfde067c8935d82190faade78941727b28f2c18)

2025-01-08 17:06 UTC, andreituicu commented on src/config/config-utils.js
> +  if (!fs.existsSync(hlxFolder)) {
Just what I was used to. I refactored now to use `fs/promises` and `fs-extra`.
Took a bit, because I had to hunt down this missing `await` that was making the `up-cli.test.js` tests to fail, as soon  I was adding an `await` to `getSiteTokenFromFile`. 🙂 
https://github.com/adobe/helix-cli/pull/2471/files#diff-a3751a8ca1ab5bdf5d4bb6b4c3861d9a81205bc01b080e57301090b6e8b34165R124

2025-01-08 17:09 UTC, andreituicu commented on src/config/config-utils.js
> +const tokenFilePath = path.join(hlxFolder, tokenFileName);
Unfortunately, this doesn't work, because `GitUtils.isIgnored` wants a separate relative path from the git project.

https://github.com/adobe/helix-cli/pull/2471/files#diff-d4deb0baa7399a2b0cb5f027dc174ec9dbfc4d9c5df876bc29f6f1503cf7aa6eR79

2025-01-10 09:30 UTC, tripodsan submitted a review, later dismissed

2025-01-12 15:58 UTC, tripodsan approved these changes

2025-01-13 06:46 UTC, merged